### PR TITLE
installed latest moment (bower_components) ...

### PR DESCRIPTION
**Pull request by mwymann**
... and successfully ran unit tests (grunt qunit).

### CODE REVIEW

**Comment by gr2m** [comment]
I'm not a bower_components pro, but I guess we can add `./bower_components` to `.gitignore`? You have to update it in `package.json` and run `npm install` to have the tests run with latest moment

**Comment by mwymann** [comment]
thats right! didn't want to make breaking changes to your project settings. but now i added bower_components to gitignore.

it is not necessary to install both npm package and bower component of moment, so I also removed the npm package. do you agree? local tests succeeded.

**Comment by gr2m** [comment]
> it is not necessary to install both npm package and bower component of moment, so I also removed the npm package. do you agree? local tests succeeded.

You can't remove the `package.json`, otherwise people will not be able to install it via npm any more :) That's also why the tests failed on travis I guess. If you remove the `node_modules` folder locally, things will fall apart :)

**Comment by gr2m** [comment]
Ah I'm sorry, I know why I left the `bower_components` folder in git. It's used on the website at http://gr2m.github.io/moment.parseFormat/. That's also why `gh-pages` is the main branch. Sorry for all the trouble, let me look quickly into this.

**Comment by gr2m** [comment]
done via 46ef27e

**Comment by mwymann** [comment]
thanks for your effort. it would be nice, if you update your bower component.

**Comment by gr2m** [comment]
for bower I need to do a new tag on github, right?

**Comment by mwymann** [comment]
that's right. You need a tag with new version number (semantic version, eg: v1.3.1) corresponding to the version in your bower.json.

for further info: http://bower.io/docs/creating-packages/#register

**Comment by gr2m** [comment]
yeah, new versions / tags get created automatically trough https://www.npmjs.com/package/semantic-release, so next time a bug gets fixed or a feature gets added, the new version gets released. But if you need it now, I'll trigger a new release manually, no biggie

**Comment by mwymann** [comment]
great. would be nice to have a release right now to update all my projects...

**Comment by gr2m** [comment]
Release is on it's way: https://travis-ci.org/gr2m/moment.parseFormat/builds/66364594

Glad to hear you are using moment.parseFormat in several projects :) Is there anything that you can show? I'd love to see how others use it.

**Comment by mwymann** [comment]
unfortunately nothing in production yet. ;)

**Comment by gr2m** [comment]
Okay :) holla when you have something to show

**Pull request closed without merging**
